spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: demopwd
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging:
    level:
      org:
        hibernate:
          type: trace

  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379